#!/bin/bash

latexmk -pdf gtex-KDM6A_vs_UTY.tex
pdfcrop gtex-KDM6A_vs_UTY.pdf gtex-KDM6A_vs_UTY.pdf
pdf2svg gtex-KDM6A_vs_UTY.pdf gtex-KDM6A_vs_UTY.svg

# cleanup
latexmk -c gtex-KDM6A_vs_UTY.tex
rm gtex-KDM6A_vs_UTY.pdf

